CXX_FLAGS=-std=c++11

all: main.cpp bot.cpp bot.hpp brokerSystem.cpp brokerSystem.hpp packetParsing.cpp packetParsing.hpp packet.cpp packet.hpp
	g++ -o poc main.cpp bot.cpp brokerSystem.cpp packetParsing.cpp packet.cpp $(CXX_FLAGS)
